# Testing and Grading all tasks 
grade:
  image: eu.gcr.io/shad-ts/grader/py-testenv
  tags:
    - docker-tester-python
  except:
    variables:
      - $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /contributing/ || $CI_COMMIT_BRANCH =~ /contributing/
      - $CI_PROJECT_NAME =~ /^public-(fall|spring)-20\d\d/
  script:
    - export CI_COMMIT_TIMESTAMP=$(git show -s --format=%cI $CI_COMMIT_SHA)  # TODO: remove after gitlab 13.4 upgrade
    - cd /opt/shad/tests
    - chmod -R 777 /opt/shad/tests
    - python3 grade.py grade
  timeout: 10 minutes

    
# Checking contribution to the main repo
check:
  image: eu.gcr.io/shad-ts/grader/py-testenv
  tags:
    - docker-tester-python
  only:
    variables:
      - $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /contributing/ || $CI_COMMIT_BRANCH =~ /contributing/
  script:
    - echo "CI_MERGE_REQUEST_SOURCE_PROJECT_PATH $CI_MERGE_REQUEST_SOURCE_PROJECT_PATH"
    - echo "CI_MERGE_REQUEST_SOURCE_PROJECT_URL $CI_MERGE_REQUEST_SOURCE_PROJECT_URL"
    - echo "CI_MERGE_REQUEST_TARGET_BRANCH_NAME $CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
    - echo "CI_MERGE_REQUEST_TARGET_BRANCH_SHA $CI_MERGE_REQUEST_TARGET_BRANCH_SHA"
    - echo "CI_MERGE_REQUEST_TARGET_PROJECT_URL $CI_MERGE_REQUEST_TARGET_PROJECT_URL"
    - echo "CI_MERGE_REQUEST_REF_PATH $CI_MERGE_REQUEST_REF_PATH"
    - echo "CI_MERGE_REQUEST_PROJECT_URL $CI_MERGE_REQUEST_PROJECT_URL"
    - echo "CI_MERGE_REQUEST_PROJECT_PATH $CI_MERGE_REQUEST_PROJECT_PATH"
    - echo "CI_MERGE_REQUEST_PROJECT_ID $CI_MERGE_REQUEST_PROJECT_ID"
    - echo "CI_MERGE_REQUEST_LABELS $CI_MERGE_REQUEST_LABELS"
    - echo "CI_MERGE_REQUEST_APPROVED $CI_MERGE_REQUEST_APPROVED"
    - echo "CI_MERGE_REQUEST_EVENT_TYPE $CI_MERGE_REQUEST_EVENT_TYPE"
    - ls -lah
    - cp -R /opt/shad/tests tests/
    - ls -lah
    - cd tests/
    - ls -lah
    - env PYTHONPATH=. python3 grade.py check
  timeout: 20 minutes
