# Testing and Grading all tasks 
grade:
  image: eu.gcr.io/shad-ts/grader/py-testenv
  tags:
    - docker-tester-python
  except:
    variables:
      - $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /contributing/ || $CI_COMMIT_BRANCH =~ /contributing/
      - $CI_PROJECT_NAME =~ /^public-(fall|spring)-20\d\d/
  script:
    - export CI_COMMIT_TIMESTAMP=$(git show -s --format=%cI $CI_COMMIT_SHA)  # TODO: remove after gitlab 13.4 upgrade
    - cd /opt/shad/tests
    - chmod -R 777 /opt/shad/tests
    - python3 -m checker grade
  timeout: 10 minutes

    
# Checking contribution to the main repo
check:
  image: eu.gcr.io/shad-ts/grader/py-testenv
  tags:
    - docker-tester-python
  only:
    variables:
      - $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /contributing/ || $CI_COMMIT_BRANCH =~ /contributing/
  script:
    - cp -R /opt/shad/tests tests/
    - cd tests/
    - env PYTHONPATH=. python3 -m checker check --contributing
  timeout: 30 minutes
